version: '3.7'

services:
    database_service:
        image: postgres:latest
        restart: always
        container_name: database_service
        networks:
            - mynetwork
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: adminadmin
          POSTGRES_DB: sensorsdb
        volumes:
          - postgres_data:/var/lib/postgresql/data
    
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin4
        ports:
          - 5050:80
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin
          - PGADMIN_DEFAULT_EMAIL=admin@example.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
          - pgadmin_data:/var/lib/pgadmin
        networks:
            - mynetwork
        depends_on: 
            - database_service

    api_services:
        build: ./api
        container_name: api_services
        networks:
            - mynetwork
        depends_on: 
            - database_service

    proxy_service:
        build: ./proxy_service
        container_name: proxy_service
        ports: 
            - 8000:80
        networks: 
            - mynetwork
        depends_on: 
            - api_services
            - database_service

volumes:
  postgres_data:
  pgadmin_data:

networks:
    mynetwork: